<?php
session_start();
include_once('../../classes/conex.php');
$link=Conectarse();
if(isset($_POST["rubro"])){
	$rubro=$_POST["rubro"];
}
if(isset($_POST["titulo"])){
	$titulo=$_POST["titulo"];
}
if(isset($_POST["subtitulo"])){
	$subtitulo=$_POST["subtitulo"];
}
if(isset($_POST["categoria"])){
	$categoria=$_POST["categoria"];
}
if(isset($_POST["imparte"])){
	$imparte=$_POST["imparte"];
}
if(isset($_POST["dirigido"])){
	$dirigido=$_POST["dirigido"];
}
if(isset($_POST["descripcion"])){
	$descripcion=$_POST["descripcion"];
}
if(isset($_POST["lugar"])){
	$lugar=$_POST["lugar"];
}
if(isset($_POST["dia"])){
	$dia=$_POST["dia"];
}
if(isset($_POST["hora_i"])){
	$hora_i=$_POST["hora_i"];
}
if(isset($_POST["hora_t"])){
	$hora_t=$_POST["hora_t"];
}
$que=mysql_query("INSERT INTO agenda_programa (titulo,subtitulo,categoria,imparte,dirigido,descripcion,lugar,dia,hora_i,hora_t) VALUES ('{$titulo}','{$subtitulo}','{$categoria}','{$imparte}','{$dirigido}','{$descripcion}','{$lugar}','{$dia}','{$hora_i}','{$hora_t}')",$link);
if(!$que){die ("Pos no se capturó el contenido, parece que: " .mysql_error());
}else{
	echo '<script>window.location.href="../../agenda.php?ruta=if_evento.php&capturado=1";</script>';
}
?>
